### PR TITLE
Force https

### PR DESCRIPTION
**Pull request by Josue-T**
Actually we can access to friendica without encryption. So force the connexion to be always encrypted.

### CODE REVIEW

**Comment by anmol26s** [comment]
The nginx file already have `rewrite ^ https://$server_name$request_uri? permanent;
` below your added code. Please remove it.

I have previously tried to implement force https but it was failing on first time opening the friendica page. see here https://github.com/friendica/friendica/pull/3464#issuecomment-317115561

Lets try it again after you do the changes.

**Comment by Josue-T** [comment]
Hello,
I have found the issue. It was at line [92](https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/nginx.conf#L92-L93) whitch had a duplication of the location instruction. So I removed and it work.
I had also fixed the indentation and also implemented the pull request #1 so you could merge this to solve the both problem. I have also tested and it work.

**Comment by Josue-T** [comment]
Hello,

Could we merge this pull request. On my side it's ready to merge.

**Comment by anmol26s** [comment]
Hi
Sorry for the late reply.
Can we first merge in the test branch? If you are sure that its working as expected and require no testing then we can go ahead and merge it in master branch.

**Comment by Josue-T** [comment]
We can do it on testing branch for some days and after if it's ok we merge in master. But in this case I think we might need to inform the users that the testing branch has been updated.

**Pull request merged**
