### PR TITLE
Upgrade to 2019.12

### PR DESCRIPTION
**Pull request by SpencerDub**
This is a work in progress.

- [x] Update version in `manifest.json`
- [x] Update `SOURCE_URL` and `SOURCE_SUM` in `/conf/addons.src`
- [x] Update URL and SUM in `/conf/app.src`
- [x] Update version in `README.md`
- [x] Update PHP5 dependencies in `/scripts/install` to PHP7.0
- [x] Update PHP5 dependencies in `/scripts/upgrade` to PHP7.0
- [x] **Unsure if necessary:** Update line 54 in `/scripts/backup` to reflect PHP7.0
- [ ] **Unsure if necessary:** Update checksum in `/check_process`, line 13 *(what is this checksum?)*

I have never done anything like this and could absolutely be missing things. Most of this list is based on @tobiasd's comments [over here](https://github.com/YunoHost-Apps/friendica_ynh/issues/20#issuecomment-576122167).

### CODE REVIEW

**Comment by SpencerDub** [comment]
There appears to be a checksum in `/check_process`, [line 13](https://github.com/YunoHost-Apps/friendica_ynh/blob/3396188976f75170f2217fcc0e6c9b5f61f7b9e9/check_process#L13). I can't tell if this needs to be updated with other checksums or not.

**Comment by Josue-T** [comment]
Hello, thanks for your work.

About dependences changes from php5 to php7 I think it's not necessary because it's automatically done by the Yunohost core which patch this.

**Comment by SpencerDub** [comment]
@Josue-T Interesting, that's good to know. If that's the case, then this PR *might* be ready to test, since I think those dependencies are the only other bit left to change.

Unless [this line from `/scripts/backup`](https://github.com/YunoHost-Apps/friendica_ynh/blob/3396188976f75170f2217fcc0e6c9b5f61f7b9e9/scripts/backup#L54) needs to be changed due to PHP version:

```
ynh_backup "/etc/php5/fpm/pool.d/$app.conf"
```

**Comment by Josue-T** [comment]
> @Josue-T Interesting, that's good to know. If that's the case, then this PR _might_ be ready to test, since I think those dependencies are the only other bit left to change.
> 
> Unless [this line from `/scripts/backup`](https://github.com/YunoHost-Apps/friendica_ynh/blob/3396188976f75170f2217fcc0e6c9b5f61f7b9e9/scripts/backup#L54) needs to be changed due to PHP version:
> 
> ```
> ynh_backup "/etc/php5/fpm/pool.d/$app.conf"
> ```

No because It replace everywhere `php5` by `php7.0`.

**Comment by SpencerDub** [comment]
@Josue-T Cool. Then yeah, I think this is ready for testing!

**Comment by SpencerDub** [comment]
As mentioned in #20, I hit a snag.

I tried to install the new version based on my fork, but the script encountered an error. I've pasted the log starting at the first warning [here](https://pastebin.com/wb6Nwe1w). The issue appears to be this:

> WARNING -   End-of-central-directory signature not found.  Either this file is not a zipfile, or it constitutes one disk of a multi-part archive.  In the latter case the central directory and zipfile comment will be found on the last disk(s) of this archive.

I'm not sure how to resolve this.

**Comment by SpencerDub** [comment]
I just updated `/conf/addons.src` to reflect the `.zip` version of the addons archive and its checksum. The installer ran all the way through, but now I have a new issue.

If you go to https://friendica.xanderwharts.us/friendica, you can see that the installation is not properly reporting the web location. I presume this is related to the fact that when I try to use the "login" button (at https://friendica.xanderwharts.us/login), it just redirects to https://login. It's as if the installation did not properly configure the "what's my URL?" setting for Friendica.

**Comment by tobiasd** [comment]
On Tue, 21 Jan 2020 18:19:07 -0800
SpencerDub <notifications@github.com> wrote:

> If you go to https://friendica.xanderwharts.us/friendica, you can see
> that the installation is not properly reporting the web location. I
> presume this is related to the fact that when I try to use the
> "login" button (at https://friendica.xanderwharts.us/login), it just
> redirects to https://login.

Strange. When I visit that page all seems to be set correctly. Clicking through the "?" menu the help / info / login pages are loaded correctly.

**Comment by SpencerDub** [comment]
Thanks for checking it out, Tobias. I reinstalled the application after commenting in here, and as you can see, it did find the hostname correctly.

**Comment by tobiasd** [comment]
Just to let you know, there is a [new Friendica release](https://github.com/friendica/friendica/releases/tag/2020.03) so you can update this pull request.

**Comment by anmol26s** [comment]
Updated to version 2020.03. Thanks for your hard work. I would like that you can improve the package. I have to implement the fail2ban for Friendica.
Please tell me if I should close this PR.

**Comment by tobiasd** [comment]
For information about Friendica and fail2ban have [a look here in the admin tools documentation](https://github.com/friendica/friendica/blob/develop/doc/tools.md#fail2ban) hope that helps with the configuration on YunoHost!

Great to see you back @anmol26s :)

**Comment by SpencerDub** [comment]
@anmol26s 
>I would like that you can improve the package.

Oh, thank you, but I don't know enough to maintain the package in the future. Copy-pasting a few different values in an install script is the limit of my relevant technical know-how. 😊

Apologies if I misunderstood.

**Pull request closed without merging**
