### PR TITLE
Fix nginx security Issue

### PR DESCRIPTION
**Pull request by Josue-T**
I found while I did a security check with gixy that using $uri instead of $request_uri is not good. So I replaced that.
I haven't checked if all part of the app run correctly after this patch, so check it before the merge.

### CODE REVIEW

**Comment by anmol26s** [comment]
Thanks, will test and merge.

**Comment by anmol26s** [comment]
@Josue-T 
Did this line had the security issue too https://github.com/YunoHost-Apps/friendica_ynh/blob/master/conf/nginx.conf#L70 ? This line will need to changed too.

**Comment by Josue-T** [comment]
Maybe, I thought the same thing than you but gixy said nothing about this line. So I don't know.

**Comment by anmol26s** [comment]
Ok, Then I will change this line too and test it.

**Comment by Josue-T** [comment]
By the #2 pull request I close it because #2 fix also this pull request.

**Pull request closed without merging**
