### PR TITLE
Use correct commit hashes for 22.10 and addons.

### PR DESCRIPTION
**Pull request by ndarilek**
## Problem

- The wrong commit hashes appear to have been used for Friendica 22.10 and its addons.

## Solution

- Use the correct hashes.

## PR Status

- [X ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tituspijean** [comment]
!testme

**Comment by tituspijean** [comment]
- [ ] Check "upgrade-but actually downgrade" from 22.10~ynh1 to 22.10~ynh2

**Comment by tio-trom** [comment]
> * [ ]  Check "upgrade-but actually downgrade" from 22.10~ynh1 to 22.10~ynh2

I am starting a conversation with the Frienedica admins and developers here https://social.trom.tf/display/dbc8dc44-1763-7a10-2c3e-2f1003184441 - it seems to be a bad idea to push now a change from the dev version (december) to a stable version (september). It will likely break the installations completely. 

The september stable version is kinda buggy anyway and they plan to release another stable in december, maybe wait for that and push an update to that when it is out.

**Comment by tio-trom** [comment]
So, Friendica's developers plan to release another stable in december. Please for now leave this package as it is, with the development branch, and update in december to the stable one once it is released, so that you upgrade from dev to stable in a chronological order. Else if you try to now update this package with an older release (the stable branch) compared to the one is currently using, then those who upgraded their ynh friendica and update again, will have their instances nuked basically, from what I understand, and no easy way (or any way) to fix it.

In essence do not update from a newere version of friendica to an older one.

**Pull request closed without merging**
