### PR TITLE
Update to 2024.03

### PR DESCRIPTION
**Pull request by mr-eshua**
## Problem

- 2024.03 version was released.

## Solution

- Tar links and hashsums were updated.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by tio-trom** [comment]
How can we trigger a test?

**Comment by mr-eshua** [comment]
!testme

**Comment by mr-eshua** [comment]
> How can we trigger a test?

But it may not work since I am not a member of Yunohost-Apps organization 🙁

**Comment by tio-trom** [comment]
!testme

**Comment by tio-trom** [comment]
hehe yeah. Please guys can you trigger a test for this? Thanks :)

**Comment by orhtej2** [comment]
!testme

**Comment by mr-eshua** [comment]
The checksums are corrected. May I ask for another test run? Thanks 🙂

**Comment by orhtej2** [comment]
!testme

**Comment by tio-trom** [comment]
Awesome! All looks good. Whenever you guys can please merge it so we can update. Thanks a lot!

**Review by MrPetovan — APPROVED** [review]

**Comment by kay0u** [comment]
Hello,

I was about to merge, but normally we merge first in testing before merging in master. The problem is that there's already work in progress on testing, so I don't really know what to do.

**Comment by tio-trom** [comment]
> Hello,
> 
> I was about to merge, but normally we merge first in testing before merging in master. The problem is that there's already work in progress on testing, so I don't really know what to do.

It is because of this? https://github.com/YunoHost-Apps/friendica_ynh/pull/131 If so see this comment https://github.com/YunoHost-Apps/friendica_ynh/pull/131#issuecomment-2019184383 maybe we can merge that one

**Pull request merged**
