### PR TITLE
Updated to 2020.04

### PR DESCRIPTION
**Pull request by anmol26s**
## Problem

- *New update available *

## Solution

- *Updated to 2020.04*
- *Started using git for fresh installs*

## PR Status

- [X] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by anmol26s** [comment]
!testme

**Comment by anmol26s** [comment]
!testme

**Comment by anmol26s** [comment]
!testme

**Comment by anmol26s** [comment]
!testme

**Comment by anmol26s** [comment]
!testme

**Comment by yalh76** [comment]
why switching to git ?
and if switching to git, why keeping app.src ?

**Comment by anmol26s** [comment]
> why switching to git ?

1. There were quite few request to use git in the packages which give flexibility to the end user to upgrade the app forcefully if they want to be ahead of the regular package cycle.  
https://github.com/YunoHost-Apps/hubzilla_ynh/issues/72
2. Even the core app developers of some apps  prefer git. 
3. And it would relief the packagers from unnecessary pressure from the end users to make the  new version available immediately.
4. It makes the migration easy for users. For example if some one leaves Yuno or joins Yuno, it would be much more easy to shift between  different ecosystems. 
5. It removes the headache to touch the app folder(for most of the apps), coping the things from app folder to temp folder and then unpacking sources and again coping the files from temp folder to main folder.
6. Git is mature enough to get the latest tags and check the hash itself make changes. And even Yunohost backup and restores is good enough to get back to previous version  after upgraded.
7. For advance users its much more easy to keep a check on developments, track commits and use all version controlling feature for the app.

>  and if switching to git, why keeping app.src ?

The git works for new installation of the app and for future upgrades. But for users who have installed the app before this release, will have to rely on the app packaging cycling, unless they themself do the changes to make the app use git. Right now while upgrade the script checks if the main folder have git. If it finds git, then it would use git to update the app otherwise it would use the normal way to update. So if  git is not there in app's main folder then normal upgrade will run and use app.src to update.

**Comment by yalh76** [comment]
As discuss, if you want to switch the package to git, no problem but previous installation has to be switched to git and for security reason it's better to use the commit ID instead of the tag

**Comment by anmol26s** [comment]
!testme

**Comment by TROMsite** [comment]
As I detailed here https://github.com/YunoHost-Apps/friendica_ynh/issues/48#issuecomment-876879220 it failed to upgrade my friendica. Error:

```

3356 WARNING _common.sh: line 33: syntax error near unexpected token `elif'
3356 WARNING _common.sh: line 33: `        elif is_there_enough_space /home; then'

587679 WARNING fatal: not a git repository (or any of the parent directories): .git
587681 WARNING ./upgrade: line 116: ynh_smart_mktemp: command not found

657350 WARNING userdel: user friendica is currently used by process 5289
657351 WARNING /usr/sbin/deluser: `/sbin/userdel friendica' returned error code 8. Exiting.
657527 WARNING /usr/sbin/delgroup: `friendica' still has `friendica' as their primary group!
```

I'd like to use git but I'd also like not to break my instance of over 100 users....let me know if I can be of any help by testing stuff.

**Pull request merged**
