### PR TITLE
Fix current non-git installs upgrade

### PR DESCRIPTION
**Pull request by mr-eshua**
## Problem

- Current upgrade procedure is very harsh on existing non-git installs and may leave them broken after all

## Solution

- Instead of complete removal old friendica directory to replace with git clonned sources, there is an attempt to convert current install directory into a git repo and update it from stable branch. This was tested enough on existing 2021.01 install and went successfully.
- Also the upgrade script rewrites local friendica config for some reason and this may lead to loosing of some user-defined changes (like admin rights in our case) and it is not a good practice. Currently I commented out the ynh_add_config helper, but maybe we need to come up with a better approach to preserve the user changes and to add possible updated config parameters from a new friendica version altogether.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by TROMsite** [comment]
This one fixed my Friendica!

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
@mr-eshua  Do you know why upgrade is failling? 🤔

**Comment by ericgaspar** [comment]
!testme

**Comment by tituspijean** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
closing with #99

**Pull request closed without merging**
