### PR TITLE
Update to 2024.08

### PR DESCRIPTION
**Pull request by tio-trom**
Updating to the latest stable, both the core and addons. Please trigger the testing.

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
Ready to merge?

**Comment by tio-trom** [comment]
yup please!

**Comment by tio-trom** [comment]
Since we have over a thousand users I usually want to wait 1-2 weeks after a release before updating to keep an eye on the release see if there are any major issues. In the meantime you can merge to testing please. I'd prefer to test on my instance in a week or so.

**Comment by OniriCorpe** [comment]
Do you want to be maintainer and get the write permission on this repo?

**Comment by tio-trom** [comment]
Sure!

**Comment by OniriCorpe** [comment]
Invite was sent!

to trigger CI tests for your future PR, juste comment “!testme”

**Comment by tio-trom** [comment]
Thanks! I will merge into main after I'll test it on my own instance,

**Pull request merged**
